name: Deploy to GCP
on:
  push:
    branches:
      - main
env:
  PROJECT_ID: custom-helix-384522
  IMAGE_TAG: latest
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  BACKEND_IMAGE_NAME: accounts-api
  BACKEND_IMAGE_TAG: ${{ github.sha }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Build and push backend Docker image
        run: |
          mvn clean package -pl accounts-api -am -DskipTests
          docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.BACKEND_IMAGE_TAG }} ./accounts-api
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.BACKEND_IMAGE_TAG }}

      - name: Configure kubectl
        run: |
          gcloud auth activate-service-account --key-file <(echo $GCP_SA_KEY)
          gcloud container clusters get-credentials my-cluster --zone us-central1-c --project $PROJECT_ID

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
