name: Deploy to GCP
on:
  push:
    branches:
      - main
env:
  PROJECT_ID: custom-helix-384522
  IMAGE_NAME: payments-app-image
  TAG: ${{ github.sha }}
  REGION: <your GCP region>
  SERVICE_NAME: my-app
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name
